spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: ${OAUTH_JWKS_URI}

  jwt:
    audience: ${AUTH_INTERNAL_AUDIENCE}

  toss:
    clientKey: ${TOSS_CLIENT_KEY}
    secretKey: ${TOSS_SECRET_KEY}