spring:
  application:
    name: payment
  config:
    import: optional:file:.env[.properties]

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

server:
  port: 8085